backend:
   name: github
   repo: Goosse/radio-seara-fm-publisher
   base_url: http://auth.radioseara.fm

locale: 'pt'
media_library:
    name: cloudinary
    config:
        cloud_name: radio-seara
        api_key: 218884594445852

collections:
  - name: 'algemas-quebradas'
    label: 'Algemas Quebradas'
    folder: 'Content/algemas-quebradas'
    filter: {field: 'index', value: 'nil'}
    create: true
    fields:
      - name: 'title'
        label: 'Titulo'
      - name: 'date'
        label: 'Data de publicação'
        widget: 'datetime'
        dateFormat: 'DD-MM-YYYY'
        timeFormat: 'H:mm \hor\a\s'
        format: 'YYYY-MM-DD H:mm'
      - name: 'body'
        label: 'Descriçao'
        widget: 'markdown'
      - name: 'audio'
        label: 'Podcast'
        widget: 'object'
        fields:
          - name: 'audio.url'
            label: 'Áudio'
            widget: 'file'
            pattern: ['.*\.(?:m4a|mp3)$', "Tem que ser um arquivo de audio m4a ou mp3"]
      - name: 'tags'
        label: 'Etiquetas'
        widget: 'string'
#      - name: 'index'
#        label: 'Index'
#        widget: 'hidden'
#        default: 'false'
  - name: 'culto-ice-nova-russas'
    label: 'Culto da ICE'
    folder: 'Content/culto-ice-nova-russas'
    filter: {field: 'index', value: 'false'}
    create: true
    fields:
      - name: 'title'
        label: 'Titulo'
      - name: 'date'
        label: 'Data de publicação'
        widget: 'datetime'
        dateFormat: 'DD-MM-YYYY'
        timeFormat: 'H:mm \hor\a\s'
        format: 'YYYY-MM-DD H:mm'
      - name: 'body'
        label: 'Descriçao'
        widget: 'markdown'
      - name: 'audio'
        label: 'Podcast'
        widget: 'object'
        fields:
          - name: 'audio.url'
            label: 'Áudio'
            widget: 'file'
            pattern: ['.*\.(?:m4a)$', "Tem que ser um arquivo de audio m4a"]
          - name: 'audio.format'
            label: 'Format'
            widget: 'hidden'
            default: 'm4a'
      - name: 'tags'
        label: 'Etiquetas'
        widget: 'string'
      - name: 'index'
        label: 'Index'
        widget: 'hidden'
        default: 'false'
  - name: 'empreendedores-de-futuro'
    label: 'Empreendedores de Futuro'
    folder: 'Content/empreendedores-de-futuro'
    filter: {field: 'index', value: 'false'}
    create: true
    fields:
      - name: 'title'
        label: 'Titulo'
      - name: 'date'
        label: 'Data de publicação'
        widget: 'datetime'
        dateFormat: 'DD-MM-YYYY'
        timeFormat: 'H:mm \hor\a\s'
        format: 'YYYY-MM-DD H:mm'
      - name: 'body'
        label: 'Descriçao'
        widget: 'markdown'
      - name: 'audio'
        label: 'Podcast'
        widget: 'object'
        fields:
          - name: 'audio.url'
            label: 'Áudio'
            widget: 'file'
            pattern: ['.*\.(?:m4a)$', "Tem que ser um arquivo de audio m4a"]
          - name: 'audio.format'
            label: 'Format'
            widget: 'hidden'
            default: 'm4a'
      - name: 'tags'
        label: 'Etiquetas'
        widget: 'string'
      - name: 'index'
        label: 'Index'
        widget: 'hidden'
        default: 'false'
